@echo off
echo R | xcopy /Y /Q C:\Users\tlepen\.remaken\packages\win-cl-14.1\xpcf\2.5.0\lib\x86_64\shared\debug\xpcf.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_atomic.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_chrono.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_container.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_context.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_contract.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_coroutine.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_date_time.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_fiber.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_filesystem.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_graph.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_iostreams.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_locale.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_log.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_log_setup.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_math_c99.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_math_c99f.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_math_c99l.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_math_tr1.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_math_tr1f.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_math_tr1l.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_nowide.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_prg_exec_monitor.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_program_options.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_random.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_regex.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_serialization.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_stacktrace_noop.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_stacktrace_windbg.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_stacktrace_windbg_cached.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_system.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_thread.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_timer.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_type_erasure.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_unit_test_framework.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_wave.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
echo R | xcopy /Y /Q C:\.conan\188a89\1\bin\boost_wserialization.dll C:\Users\tlepen\.remaken\packages\SolARBuild\win-cl-14.1\SolARFramework\0.9.5\lib\x86_64\shared\debug\
